// ===================================================
// Built-in Global Fields — Seed Data
// ===================================================
// These are the default fields available in every vBrain instance.
// Users can create more via the Field Library UI.

import type { GlobalFieldInsert } from './types';

export const BUILTIN_FIELDS: GlobalFieldInsert[] = [
  // ─── Composite Fields ─────────────────────────────
  {
    meta_key: 'full_name',
    label: { he: 'שם מלא', en: 'Full Name', ru: 'Полное имя' },
    description: { he: 'שם פרטי + שם משפחה', en: 'First name + last name', ru: 'Имя + фамилия' },
    field_type: 'composite',
    is_composite: true,
    sub_fields: [
      { meta_key: 'first_name', label: { he: 'שם פרטי', en: 'First Name', ru: 'Имя' }, field_type: 'text' },
      { meta_key: 'last_name', label: { he: 'שם משפחה', en: 'Last Name', ru: 'Фамилия' }, field_type: 'text' },
    ],
    display_template: '{first_name} {last_name}',
    options: [],
    validation: {},
    default_value: null,
    icon: 'User',
    category: 'contact',
    sort_order: 0,
  },
  {
    meta_key: 'business',
    label: { he: 'בית עסק', en: 'Business', ru: 'Бизнес' },
    description: { he: 'שם עסק + מספר זיהוי', en: 'Business name + ID number', ru: 'Название + ID' },
    field_type: 'composite',
    is_composite: true,
    sub_fields: [
      { meta_key: 'business_name', label: { he: 'שם העסק', en: 'Business Name', ru: 'Название' }, field_type: 'text' },
      { meta_key: 'business_id', label: { he: 'ח.פ / ע.מ', en: 'Business ID', ru: 'ИНН' }, field_type: 'text' },
    ],
    display_template: '{business_name} ({business_id})',
    options: [],
    validation: {},
    default_value: null,
    icon: 'Building2',
    category: 'business',
    sort_order: 1,
  },
  {
    meta_key: 'address',
    label: { he: 'כתובת', en: 'Address', ru: 'Адрес' },
    description: { he: 'רחוב + עיר + מיקוד', en: 'Street + city + zip', ru: 'Улица + город + индекс' },
    field_type: 'composite',
    is_composite: true,
    sub_fields: [
      { meta_key: 'street', label: { he: 'רחוב', en: 'Street', ru: 'Улица' }, field_type: 'text' },
      { meta_key: 'city', label: { he: 'עיר', en: 'City', ru: 'Город' }, field_type: 'text' },
      { meta_key: 'zip', label: { he: 'מיקוד', en: 'Zip', ru: 'Индекс' }, field_type: 'text' },
    ],
    display_template: '{street}, {city} {zip}',
    options: [],
    validation: {},
    default_value: null,
    icon: 'MapPin',
    category: 'contact',
    sort_order: 2,
  },

  // ─── Simple Fields ────────────────────────────────
  {
    meta_key: 'phone',
    label: { he: 'טלפון', en: 'Phone', ru: 'Телефон' },
    description: { he: 'מספר טלפון', en: 'Phone number', ru: 'Номер телефона' },
    field_type: 'phone',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'Phone',
    category: 'contact',
    sort_order: 10,
  },
  {
    meta_key: 'email',
    label: { he: 'מייל', en: 'Email', ru: 'Электронная почта' },
    description: { he: 'כתובת אימייל', en: 'Email address', ru: 'Адрес электронной почты' },
    field_type: 'email',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'Mail',
    category: 'contact',
    sort_order: 11,
  },
  {
    meta_key: 'status',
    label: { he: 'סטטוס', en: 'Status', ru: 'Статус' },
    description: { he: 'סטטוס נוכחי', en: 'Current status', ru: 'Текущий статус' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'todo', label: { he: 'לביצוע', en: 'To Do', ru: 'К выполнению' }, color: '#60a5fa' },
      { value: 'in-progress', label: { he: 'בביצוע', en: 'In Progress', ru: 'В работе' }, color: '#f472b6' },
      { value: 'done', label: { he: 'הושלם', en: 'Done', ru: 'Готово' }, color: '#34d399' },
      { value: 'cancelled', label: { he: 'בוטל', en: 'Cancelled', ru: 'Отменено' }, color: '#ef4444' },
    ],
    validation: {},
    default_value: 'todo',
    icon: 'CircleDot',
    category: 'general',
    sort_order: 20,
  },
  {
    meta_key: 'priority',
    label: { he: 'עדיפות', en: 'Priority', ru: 'Приоритет' },
    description: { he: 'רמת עדיפות', en: 'Priority level', ru: 'Уровень приоритета' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'low', label: { he: 'נמוכה', en: 'Low', ru: 'Низкий' }, color: '#94a3b8' },
      { value: 'medium', label: { he: 'בינונית', en: 'Medium', ru: 'Средний' }, color: '#fbbf24' },
      { value: 'high', label: { he: 'גבוהה', en: 'High', ru: 'Высокий' }, color: '#fb923c' },
      { value: 'urgent', label: { he: 'דחופה', en: 'Urgent', ru: 'Срочный' }, color: '#ef4444' },
    ],
    validation: {},
    default_value: null,
    icon: 'Flag',
    category: 'general',
    sort_order: 21,
  },
  {
    meta_key: 'due_date',
    label: { he: 'תאריך יעד', en: 'Due Date', ru: 'Срок' },
    description: { he: 'תאריך יעד לסיום', en: 'Target completion date', ru: 'Целевая дата завершения' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'CalendarDays',
    category: 'general',
    sort_order: 22,
  },
  {
    meta_key: 'assignee',
    label: { he: 'אחראי', en: 'Assignee', ru: 'Ответственный' },
    description: { he: 'האדם האחראי', en: 'Person responsible', ru: 'Ответственное лицо' },
    field_type: 'person',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'UserCircle',
    category: 'general',
    sort_order: 23,
  },
  {
    meta_key: 'tags',
    label: { he: 'תגיות', en: 'Tags', ru: 'Теги' },
    description: { he: 'תגיות לסיווג', en: 'Classification tags', ru: 'Теги классификации' },
    field_type: 'multi-select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'Tags',
    category: 'general',
    sort_order: 24,
  },
  {
    meta_key: 'url',
    label: { he: 'קישור', en: 'URL', ru: 'Ссылка' },
    description: { he: 'כתובת אינטרנט', en: 'Web address', ru: 'Веб-адрес' },
    field_type: 'url',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'Link',
    category: 'general',
    sort_order: 25,
  },
  {
    meta_key: 'notes',
    label: { he: 'הערות', en: 'Notes', ru: 'Заметки' },
    description: { he: 'הערות חופשיות', en: 'Free-form notes', ru: 'Свободные заметки' },
    field_type: 'text',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'StickyNote',
    category: 'general',
    sort_order: 26,
  },
  {
    meta_key: 'is_active',
    label: { he: 'פעיל', en: 'Active', ru: 'Активен' },
    description: { he: 'האם פעיל?', en: 'Is active?', ru: 'Активен?' },
    field_type: 'checkbox',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: true,
    icon: 'CheckSquare',
    category: 'general',
    sort_order: 27,
  },

  // ─── Dev / Project Fields ──────────────────────────
  {
    meta_key: 'sprint',
    label: { he: 'ספרינט', en: 'Sprint', ru: 'Спринт' },
    description: { he: 'ספרינט נוכחי', en: 'Current sprint', ru: 'Текущий спринт' },
    field_type: 'text',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'Zap',
    category: 'project',
    sort_order: 30,
  },
  {
    meta_key: 'story_points',
    label: { he: 'נקודות סיפור', en: 'Story Points', ru: 'Story Points' },
    description: { he: 'הערכת מאמץ', en: 'Effort estimate', ru: 'Оценка трудозатрат' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0, max: 100 },
    default_value: null,
    icon: 'Hash',
    category: 'project',
    sort_order: 31,
  },
  {
    meta_key: 'acceptance_criteria',
    label: { he: 'קריטריוני קבלה', en: 'Acceptance Criteria', ru: 'Критерии приёмки' },
    description: { he: 'תנאי סיום', en: 'Definition of done', ru: 'Критерии завершения' },
    field_type: 'text',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'ListChecks',
    category: 'project',
    sort_order: 32,
  },
  {
    meta_key: 'pr_link',
    label: { he: 'קישור PR', en: 'PR Link', ru: 'Ссылка PR' },
    description: { he: 'קישור ל-Pull Request', en: 'Pull Request link', ru: 'Ссылка на Pull Request' },
    field_type: 'url',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'GitPullRequest',
    category: 'project',
    sort_order: 33,
  },
  {
    meta_key: 'environment',
    label: { he: 'סביבה', en: 'Environment', ru: 'Среда' },
    description: { he: 'סביבת פריסה', en: 'Deployment environment', ru: 'Среда развёртывания' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'dev', label: { he: 'פיתוח', en: 'Dev', ru: 'Разработка' }, color: '#60a5fa' },
      { value: 'staging', label: { he: 'סטיגינג', en: 'Staging', ru: 'Стейджинг' }, color: '#fbbf24' },
      { value: 'production', label: { he: 'פרודקשן', en: 'Production', ru: 'Продакшн' }, color: '#34d399' },
    ],
    validation: {},
    default_value: null,
    icon: 'Server',
    category: 'project',
    sort_order: 34,
  },
  {
    meta_key: 'branch',
    label: { he: 'ענף', en: 'Branch', ru: 'Ветка' },
    description: { he: 'שם הענף ב-Git', en: 'Git branch name', ru: 'Имя ветки Git' },
    field_type: 'text',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'GitBranch',
    category: 'project',
    sort_order: 35,
  },
  {
    meta_key: 'reviewer',
    label: { he: 'סוקר', en: 'Reviewer', ru: 'Ревьюер' },
    description: { he: 'סוקר הקוד', en: 'Code reviewer', ru: 'Ревьюер кода' },
    field_type: 'person',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'UserCheck',
    category: 'project',
    sort_order: 36,
  },
  {
    meta_key: 'start_date',
    label: { he: 'תאריך התחלה', en: 'Start Date', ru: 'Дата начала' },
    description: { he: 'תאריך תחילת העבודה', en: 'Work start date', ru: 'Дата начала работы' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'CalendarPlus',
    category: 'project',
    sort_order: 37,
  },
  {
    meta_key: 'estimated_hours',
    label: { he: 'שעות מוערכות', en: 'Estimated Hours', ru: 'Оценка часов' },
    description: { he: 'הערכת זמן בשעות', en: 'Time estimate in hours', ru: 'Оценка времени в часах' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0 },
    default_value: null,
    icon: 'Clock',
    category: 'project',
    sort_order: 38,
  },
  {
    meta_key: 'actual_hours',
    label: { he: 'שעות בפועל', en: 'Actual Hours', ru: 'Фактические часы' },
    description: { he: 'זמן בפועל בשעות', en: 'Actual time spent in hours', ru: 'Фактическое время в часах' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0 },
    default_value: null,
    icon: 'Timer',
    category: 'project',
    sort_order: 39,
  },

  // ─── CRM / Finance Fields ─────────────────────────
  {
    meta_key: 'deal_value',
    label: { he: 'ערך עסקה', en: 'Deal Value', ru: 'Сумма сделки' },
    description: { he: 'ערך כספי של העסקה', en: 'Monetary deal value', ru: 'Денежная сумма сделки' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0 },
    default_value: null,
    icon: 'DollarSign',
    category: 'finance',
    sort_order: 40,
  },
  {
    meta_key: 'expected_close',
    label: { he: 'סגירה צפויה', en: 'Expected Close', ru: 'Ожидаемое закрытие' },
    description: { he: 'תאריך סגירה צפוי', en: 'Expected close date', ru: 'Ожидаемая дата закрытия' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'CalendarCheck',
    category: 'finance',
    sort_order: 41,
  },
  {
    meta_key: 'pipeline_stage',
    label: { he: 'שלב צנרת', en: 'Pipeline Stage', ru: 'Этап воронки' },
    description: { he: 'שלב בצנרת המכירות', en: 'Sales pipeline stage', ru: 'Этап воронки продаж' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'lead', label: { he: 'ליד', en: 'Lead', ru: 'Лид' }, color: '#94a3b8' },
      { value: 'qualified', label: { he: 'מוסמך', en: 'Qualified', ru: 'Квалифицирован' }, color: '#60a5fa' },
      { value: 'proposal', label: { he: 'הצעה', en: 'Proposal', ru: 'Предложение' }, color: '#a78bfa' },
      { value: 'negotiation', label: { he: 'משא ומתן', en: 'Negotiation', ru: 'Переговоры' }, color: '#fbbf24' },
      { value: 'closed_won', label: { he: 'נסגר ✓', en: 'Closed Won', ru: 'Закрыто ✓' }, color: '#34d399' },
      { value: 'closed_lost', label: { he: 'נסגר ✗', en: 'Closed Lost', ru: 'Закрыто ✗' }, color: '#ef4444' },
    ],
    validation: {},
    default_value: 'lead',
    icon: 'TrendingUp',
    category: 'finance',
    sort_order: 42,
  },
  {
    meta_key: 'probability',
    label: { he: 'הסתברות', en: 'Probability', ru: 'Вероятность' },
    description: { he: 'הסתברות סגירה (%)', en: 'Close probability (%)', ru: 'Вероятность закрытия (%)' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0, max: 100 },
    default_value: null,
    icon: 'Percent',
    category: 'finance',
    sort_order: 43,
  },
  {
    meta_key: 'commission',
    label: { he: 'עמלה', en: 'Commission', ru: 'Комиссия' },
    description: { he: 'עמלה על העסקה', en: 'Deal commission', ru: 'Комиссия по сделке' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 0 },
    default_value: null,
    icon: 'Coins',
    category: 'finance',
    sort_order: 44,
  },
  {
    meta_key: 'lead_source',
    label: { he: 'מקור ליד', en: 'Lead Source', ru: 'Источник лида' },
    description: { he: 'מאיפה הגיע הליד', en: 'Where the lead came from', ru: 'Откуда пришёл лид' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'website', label: { he: 'אתר', en: 'Website', ru: 'Сайт' } },
      { value: 'referral', label: { he: 'הפניה', en: 'Referral', ru: 'Рекомендация' } },
      { value: 'cold_call', label: { he: 'שיחה קרה', en: 'Cold Call', ru: 'Холодный звонок' } },
      { value: 'event', label: { he: 'אירוע', en: 'Event', ru: 'Мероприятие' } },
      { value: 'ad', label: { he: 'פרסום', en: 'Ad', ru: 'Реклама' } },
    ],
    validation: {},
    default_value: null,
    icon: 'Megaphone',
    category: 'finance',
    sort_order: 45,
  },
  {
    meta_key: 'qualification_score',
    label: { he: 'ציון כשירות', en: 'Qualification Score', ru: 'Оценка квалификации' },
    description: { he: 'ציון כשירות 1-10', en: 'Qualification score 1-10', ru: 'Оценка квалификации 1-10' },
    field_type: 'number',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: { min: 1, max: 10 },
    default_value: null,
    icon: 'Star',
    category: 'finance',
    sort_order: 46,
  },
  {
    meta_key: 'conversion_date',
    label: { he: 'תאריך המרה', en: 'Conversion Date', ru: 'Дата конверсии' },
    description: { he: 'מתי הליד הפך לעסקה', en: 'When lead converted to deal', ru: 'Когда лид стал сделкой' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'ArrowRightCircle',
    category: 'finance',
    sort_order: 47,
  },
  {
    meta_key: 'agreement_type',
    label: { he: 'סוג הסכם', en: 'Agreement Type', ru: 'Тип соглашения' },
    description: { he: 'סוג ההסכם', en: 'Type of agreement', ru: 'Тип соглашения' },
    field_type: 'select',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [
      { value: 'service', label: { he: 'שירות', en: 'Service', ru: 'Сервис' } },
      { value: 'rental', label: { he: 'השכרה', en: 'Rental', ru: 'Аренда' } },
      { value: 'sale', label: { he: 'מכירה', en: 'Sale', ru: 'Продажа' } },
      { value: 'partnership', label: { he: 'שותפות', en: 'Partnership', ru: 'Партнёрство' } },
    ],
    validation: {},
    default_value: null,
    icon: 'FileSignature',
    category: 'finance',
    sort_order: 48,
  },
  {
    meta_key: 'effective_date',
    label: { he: 'תאריך תחילה', en: 'Effective Date', ru: 'Дата вступления' },
    description: { he: 'תאריך תחילת ההסכם', en: 'Agreement effective date', ru: 'Дата вступления в силу' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'CalendarRange',
    category: 'finance',
    sort_order: 49,
  },
  {
    meta_key: 'expiry_date',
    label: { he: 'תאריך תפוגה', en: 'Expiry Date', ru: 'Дата истечения' },
    description: { he: 'תאריך תפוגת ההסכם', en: 'Agreement expiry date', ru: 'Дата истечения соглашения' },
    field_type: 'date',
    is_composite: false,
    sub_fields: [],
    display_template: null,
    options: [],
    validation: {},
    default_value: null,
    icon: 'CalendarX',
    category: 'finance',
    sort_order: 50,
  },
];

// ─── Built-in Field Groups ──────────────────────────
import type { FieldGroupInsert } from './types';

export const BUILTIN_FIELD_GROUPS: FieldGroupInsert[] = [
  {
    meta_key: 'work_experience',
    label: { he: 'ניסיון תעסוקתי', en: 'Work Experience', ru: 'Опыт работы' },
    description: { he: 'רשומות ניסיון עבודה חוזרות', en: 'Repeating work experience entries', ru: 'Записи об опыте работы' },
    field_refs: ['business_name', 'role', 'start_date', 'end_date'],
    icon: 'Briefcase',
    category: 'hr',
    sort_order: 0,
  },
  {
    meta_key: 'call_log',
    label: { he: 'לוג שיחות', en: 'Call Log', ru: 'Журнал звонков' },
    description: { he: 'תיעוד שיחות חוזר', en: 'Repeating call documentation', ru: 'Журнал документации звонков' },
    field_refs: ['date', 'summary', 'action', 'caller'],
    icon: 'PhoneCall',
    category: 'general',
    sort_order: 1,
  },
  {
    meta_key: 'education',
    label: { he: 'השכלה', en: 'Education', ru: 'Образование' },
    description: { he: 'רשומות השכלה חוזרות', en: 'Repeating education entries', ru: 'Записи об образовании' },
    field_refs: ['institution', 'degree', 'year'],
    icon: 'GraduationCap',
    category: 'hr',
    sort_order: 2,
  },
];
