// ─── Component Registry — vBrain.io ───────────────────────────────────
// Catalog of all custom components in the project.
// Follows the WidgetRegistry.ts pattern: typed entries + lookup functions.

export type ComponentCategory =
  | 'layout'
  | 'navigation'
  | 'data-display'
  | 'input'
  | 'feedback'
  | 'canvas'
  | 'editor'
  | 'widget';

export type ComponentStatus = 'stable' | 'beta' | 'deprecated';

export interface ComponentProp {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface ComponentEntry {
  id: string;
  name: string;
  nameHe: string;
  description: string;
  descriptionHe: string;
  category: ComponentCategory;
  filePath: string;
  usedIn: string[];
  dependencies: string[];
  hasI18n: boolean;
  hasCcId: boolean;
  status: ComponentStatus;
  props?: ComponentProp[];
}

// ─── Category metadata ──────────────────────────────────────────────

export const CATEGORY_COLORS: Record<ComponentCategory, { color: string; bg: string }> = {
  layout:         { color: '#60a5fa', bg: 'rgba(96,165,250,0.12)' },
  navigation:     { color: '#818cf8', bg: 'rgba(129,140,248,0.12)' },
  'data-display': { color: '#34d399', bg: 'rgba(52,211,153,0.12)' },
  input:          { color: '#fbbf24', bg: 'rgba(251,191,36,0.12)' },
  feedback:       { color: '#fb7185', bg: 'rgba(251,113,133,0.12)' },
  canvas:         { color: '#22d3ee', bg: 'rgba(34,211,238,0.12)' },
  editor:         { color: '#c084fc', bg: 'rgba(192,132,252,0.12)' },
  widget:         { color: '#f472b6', bg: 'rgba(244,114,182,0.12)' },
};

// ─── Registry ───────────────────────────────────────────────────────

export const componentRegistry: ComponentEntry[] = [
  // ── Layout ────────────────────────────────────────────────────────
  {
    id: 'dashboard-shell',
    name: 'DashboardShell',
    nameHe: 'מסגרת ראשית',
    description: 'Root shell wrapping sidebar, top bar, and content area. Manages layout and AI panel positioning.',
    descriptionHe: 'מסגרת ראשית העוטפת סרגל צד, סרגל עליון ואזור תוכן. מנהלת פריסה ומיקום פאנל AI.',
    category: 'layout',
    filePath: 'components/command-center/DashboardShell.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['sidebar', 'top-bar'],
    hasI18n: false,
    hasCcId: true,
    status: 'stable',
    props: [
      { name: 'children', type: 'ReactNode', required: true, description: 'Page content' },
    ],
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    nameHe: 'סרגל צד',
    description: 'Main navigation sidebar with tab links, logo, footer tagline, and visibility modes (visible/float/hidden).',
    descriptionHe: 'סרגל ניווט ראשי עם קישורי לשוניות, לוגו, תגית תחתית ומצבי נראות (גלוי/צף/מוסתר).',
    category: 'layout',
    filePath: 'components/command-center/Sidebar.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: true,
    status: 'stable',
    props: [
      { name: 'activeTab', type: 'string', required: true, description: 'Currently active tab ID' },
    ],
  },
  {
    id: 'top-bar',
    name: 'TopBar',
    nameHe: 'סרגל עליון',
    description: 'Fixed 48px bar with draggable widget grid. Handles widget positioning, drag-and-drop, and resize observer.',
    descriptionHe: 'סרגל קבוע 48px עם רשת ווידג\'טים ניתנת לגרירה. מנהל מיקום, גרירה ותצפית גודל.',
    category: 'layout',
    filePath: 'components/command-center/TopBar.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['widget-wrapper', 'widget-store', 'apps-drawer'],
    hasI18n: true,
    hasCcId: true,
    status: 'stable',
  },
  {
    id: 'page-header',
    name: 'PageHeader',
    nameHe: 'כותרת עמוד',
    description: 'Shared header for all 9 dashboard pages with title, description, pin-to-favorites, and optional guide overlay trigger.',
    descriptionHe: 'כותרת משותפת ל-9 עמודי הדשבורד עם כותרת, תיאור, הצמדה למועדפים והפעלת מדריך.',
    category: 'layout',
    filePath: 'components/command-center/PageHeader.tsx',
    usedIn: ['/dashboard/layers', '/dashboard/editor', '/dashboard/story-map', '/dashboard/design-system', '/dashboard/admin', '/dashboard/automations'],
    dependencies: [],
    hasI18n: true,
    hasCcId: true,
    status: 'stable',
    props: [
      { name: 'pageKey', type: 'string', required: true, description: 'i18n key for page title/description' },
    ],
  },
  {
    id: 'context-menu',
    name: 'ContextMenu',
    nameHe: 'תפריט הקשר',
    description: 'Generic right-click context menu with positioned dropdown, keyboard navigation, and auto-dismiss.',
    descriptionHe: 'תפריט הקשר כללי עם מיקום אוטומטי, ניווט מקלדת וסגירה אוטומטית.',
    category: 'layout',
    filePath: 'components/command-center/ContextMenu.tsx',
    usedIn: ['/dashboard/layers', '/dashboard/story-map'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },

  // ── Navigation ────────────────────────────────────────────────────
  {
    id: 'story-board',
    name: 'StoryBoard',
    nameHe: 'לוח סיפור',
    description: 'Phase 3 story map board container. Manages columns, drag _context, and epic/story hierarchy.',
    descriptionHe: 'מכולת לוח מפת סיפור שלב 3. מנהל עמודות, הקשר גרירה והיררכיית אפיק/סיפור.',
    category: 'navigation',
    filePath: 'components/command-center/StoryBoard.tsx',
    usedIn: ['/dashboard/story-map'],
    dependencies: ['story-column', 'story-card'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },

  // ── Data Display ──────────────────────────────────────────────────
  {
    id: 'project-card',
    name: 'ProjectCard',
    nameHe: 'כרטיס פרויקט',
    description: 'Project list item showing name, status, layer, health score, and metadata. Used in Layers page.',
    descriptionHe: 'פריט רשימת פרויקט המציג שם, סטטוס, שכבה, ציון בריאות ומטא-דאטה. בשימוש בעמוד שכבות.',
    category: 'data-display',
    filePath: 'components/command-center/ProjectCard.tsx',
    usedIn: ['/dashboard/layers'],
    dependencies: ['health-badge'],
    hasI18n: true,
    hasCcId: true,
    status: 'stable',
    props: [
      { name: 'project', type: 'Project', required: true, description: 'Project data object' },
      { name: 'onClick', type: '() => void', required: false, description: 'Click handler' },
    ],
  },
  {
    id: 'health-badge',
    name: 'HealthBadge',
    nameHe: 'תג בריאות',
    description: 'Color-coded health score indicator (green/amber/red) with numerical value.',
    descriptionHe: 'מחוון ציון בריאות מקודד צבע (ירוק/כתום/אדום) עם ערך מספרי.',
    category: 'data-display',
    filePath: 'components/command-center/HealthBadge.tsx',
    usedIn: ['/dashboard/layers'],
    dependencies: [],
    hasI18n: false,
    hasCcId: true,
    status: 'stable',
    props: [
      { name: 'score', type: 'number', required: true, description: 'Health score 0-100' },
    ],
  },
  {
    id: 'story-card',
    name: 'StoryCard',
    nameHe: 'כרטיס סיפור',
    description: 'Draggable story/epic card for the story map. Supports sub-items, color coding, and inline editing.',
    descriptionHe: 'כרטיס סיפור/אפיק ניתן לגרירה עבור מפת הסיפור. תומך תתי-פריטים, קידוד צבע ועריכה.',
    category: 'data-display',
    filePath: 'components/command-center/StoryCard.tsx',
    usedIn: ['/dashboard/story-map'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
    props: [
      { name: 'card', type: 'StoryCardData', required: true, description: 'Card data (text, type, color, subs)' },
      { name: 'onEdit', type: '(id, data) => void', required: false, description: 'Edit callback' },
    ],
  },
  {
    id: 'story-column',
    name: 'StoryColumn',
    nameHe: 'עמודת סיפור',
    description: 'Droppable column container for story map. Holds sorted StoryCards with add button.',
    descriptionHe: 'מכולת עמודה לניתוח סיפור. מחזיקה כרטיסי סיפור ממוינים עם כפתור הוספה.',
    category: 'data-display',
    filePath: 'components/command-center/StoryColumn.tsx',
    usedIn: ['/dashboard/story-map'],
    dependencies: ['story-card'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'color-picker',
    name: 'ColorPicker',
    nameHe: 'בוחר צבע',
    description: 'HSL color picker with hue/saturation sliders, hex input, and preset palette. Used in Settings and style overrides.',
    descriptionHe: 'בוחר צבע HSL עם מחוונים, קלט hex ופלטת מוכנים מראש. בשימוש בהגדרות ודריסות סגנון.',
    category: 'data-display',
    filePath: 'components/command-center/ColorPicker.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },

  // ── Input / Feedback ──────────────────────────────────────────────
  {
    id: 'edit-toolbar',
    name: 'EditToolbar',
    nameHe: 'סרגל עריכה',
    description: 'Floating toolbar for inline editing actions (bold, italic, link, etc.) in story cards.',
    descriptionHe: 'סרגל צף לפעולות עריכה בתוך כרטיסי סיפור (מודגש, נטוי, קישור וכו\').',
    category: 'input',
    filePath: 'components/command-center/EditToolbar.tsx',
    usedIn: ['/dashboard/story-map'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'guide-overlay',
    name: 'GuideOverlay',
    nameHe: 'שכבת מדריך',
    description: 'Transparent overlay highlighting UI elements with tooltips. Triggered by "?" button in PageHeader.',
    descriptionHe: 'שכבה שקופה המדגישה אלמנטי UI עם הסברים. מופעלת מכפתור "?" בכותרת העמוד.',
    category: 'feedback',
    filePath: 'components/command-center/GuideOverlay.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },

  // ── Canvas ────────────────────────────────────────────────────────
  {
    id: 'canvas-editor',
    name: 'CanvasEditor',
    nameHe: 'עורך קנבס',
    description: 'Main canvas editing surface with infinite scroll, zoom controls, and grid snapping.',
    descriptionHe: 'משטח עריכת קנבס ראשי עם גלילה אינסופית, בקרות זום והצמדה לרשת.',
    category: 'canvas',
    filePath: 'components/canvas/CanvasEditor.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: ['canvas-toolbar', 'canvas-grid', 'editor-zone'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'canvas-toolbar',
    name: 'CanvasToolbar',
    nameHe: 'סרגל קנבס',
    description: 'Toolbar with canvas-specific actions: add field, zoom, undo/redo, grid toggle.',
    descriptionHe: 'סרגל כלים עם פעולות ספציפיות לקנבס: הוספת שדה, זום, ביטול/חזרה, רשת.',
    category: 'canvas',
    filePath: 'components/canvas/CanvasToolbar.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'canvas-field-item',
    name: 'CanvasFieldItem',
    nameHe: 'שדה קנבס',
    description: 'Individual field rendered on the canvas. Draggable, resizable, and editable inline.',
    descriptionHe: 'שדה בודד המוצג על הקנבס. ניתן לגרירה, שינוי גודל ועריכה.',
    category: 'canvas',
    filePath: 'components/canvas/CanvasFieldItem.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'canvas-grid',
    name: 'CanvasGrid',
    nameHe: 'רשת קנבס',
    description: 'SVG dot grid background for the canvas editor. Supports zoom scaling.',
    descriptionHe: 'רקע רשת נקודות SVG לעורך הקנבס. תומך שינוי קנה מידה.',
    category: 'canvas',
    filePath: 'components/canvas/CanvasGrid.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'editor-zone',
    name: 'EditorZone',
    nameHe: 'אזור עריכה',
    description: 'Drop zone for canvas items. Handles drop events and placement validation.',
    descriptionHe: 'אזור שחרור לפריטי קנבס. מטפל באירועי שחרור ואימות מיקום.',
    category: 'canvas',
    filePath: 'components/canvas/EditorZone.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },

  // ── Editor (Tiptap) ──────────────────────────────────────────────
  {
    id: 'tiptap-editor',
    name: 'TiptapEditor',
    nameHe: 'עורך Tiptap',
    description: 'Rich text block editor wrapping Tiptap. Supports slash commands, floating toolbar, and document save/load.',
    descriptionHe: 'עורך טקסט עשיר עוטף Tiptap. תומך פקודות סלאש, סרגל צף ושמירה/טעינה.',
    category: 'editor',
    filePath: 'components/editor/TiptapEditor.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: ['floating-toolbar', 'slash-command-menu', 'block-handle', 'color-menu'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'floating-toolbar',
    name: 'FloatingToolbar',
    nameHe: 'סרגל צף',
    description: 'Bubble menu appearing on text selection with formatting options (bold, italic, code, link, highlight).',
    descriptionHe: 'תפריט בועה המופיע בבחירת טקסט עם אפשרויות עיצוב (מודגש, נטוי, קוד, קישור, הדגשה).',
    category: 'editor',
    filePath: 'components/editor/FloatingToolbar.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'slash-command-menu',
    name: 'SlashCommandMenu',
    nameHe: 'תפריט סלאש',
    description: 'Tiptap slash command dropdown for inserting blocks: heading, list, quote, code, image, divider.',
    descriptionHe: 'תפריט פקודות סלאש להכנסת בלוקים: כותרת, רשימה, ציטוט, קוד, תמונה, מפריד.',
    category: 'editor',
    filePath: 'components/editor/SlashCommandMenu.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'block-handle',
    name: 'BlockHandle',
    nameHe: 'ידית בלוק',
    description: 'Drag handle appearing on block hover for reordering content blocks in the editor.',
    descriptionHe: 'ידית גרירה המופיעה בריחוף על בלוק לשינוי סדר בלוקי תוכן בעורך.',
    category: 'editor',
    filePath: 'components/editor/BlockHandle.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'color-menu',
    name: 'ColorMenu',
    nameHe: 'תפריט צבע',
    description: 'Color picker dropdown for text and highlight colors in the editor toolbar.',
    descriptionHe: 'תפריט בוחר צבע עבור צבעי טקסט והדגשה בסרגל העורך.',
    category: 'editor',
    filePath: 'components/editor/ColorMenu.tsx',
    usedIn: ['/dashboard/editor'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },

  // ── Widgets ───────────────────────────────────────────────────────
  {
    id: 'widget-wrapper',
    name: 'WidgetWrapper',
    nameHe: 'עוטף ווידג\'ט',
    description: 'Renders widget bar content + dropdown/modal/side-panel. Handles hover, click, drag, and panel positioning.',
    descriptionHe: 'מציג תוכן ווידג\'ט בסרגל + פאנל נפתח/מודל/צד. מנהל ריחוף, לחיצה, גרירה ומיקום.',
    category: 'widget',
    filePath: 'components/command-center/widgets/WidgetWrapper.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: false,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'widget-store',
    name: 'WidgetStore',
    nameHe: 'חנות ווידג\'טים',
    description: 'Widget library browser showing active and coming-soon widgets. Allows toggling placement (toolbar/apps/disabled).',
    descriptionHe: 'דפדפן ספריית ווידג\'טים המציג פעילים ובקרוב. מאפשר החלפת מיקום (סרגל/אפליקציות/כבוי).',
    category: 'widget',
    filePath: 'components/command-center/widgets/WidgetStore.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['widget-settings'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'widget-settings',
    name: 'WidgetSettings',
    nameHe: 'הגדרות ווידג\'ט',
    description: 'Per-widget settings modal for size, visibility, and hover delay configuration.',
    descriptionHe: 'מודל הגדרות לכל ווידג\'ט — גודל, נראות וזמן ריחוף.',
    category: 'widget',
    filePath: 'components/command-center/widgets/WidgetSettings.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'search-widget',
    name: 'SearchWidget',
    nameHe: 'ווידג\'ט חיפוש',
    description: 'Cmd+K spotlight search widget. Modal mode with fuzzy search across projects, documents, and pages.',
    descriptionHe: 'ווידג\'ט חיפוש Cmd+K. מצב מודל עם חיפוש מטושטש בפרויקטים, מסמכים ודפים.',
    category: 'widget',
    filePath: 'components/command-center/widgets/SearchWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'ai-widget',
    name: 'AIWidget',
    nameHe: 'ווידג\'ט AI',
    description: 'AI chat assistant with side-panel mode. Supports page context injection and streaming responses.',
    descriptionHe: 'עוזר צ\'אט AI עם מצב פאנל צד. תומך הזרקת הקשר עמוד ותשובות זורמות.',
    category: 'widget',
    filePath: 'components/command-center/widgets/AIWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'beta',
  },
  {
    id: 'quick-create-widget',
    name: 'QuickCreateWidget',
    nameHe: 'ווידג\'ט יצירה מהירה',
    description: 'Quick create dropdown for new documents, projects, and tasks with template selection.',
    descriptionHe: 'נפתח ליצירה מהירה של מסמכים, פרויקטים ומשימות עם בחירת תבנית.',
    category: 'widget',
    filePath: 'components/command-center/widgets/QuickCreateWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'favorites-widget',
    name: 'FavoritesWidget',
    nameHe: 'ווידג\'ט מועדפים',
    description: 'Pinned pages with drag reorder. Dropdown panel showing saved favorites with folder support.',
    descriptionHe: 'דפים מוצמדים עם גרירה לסידור. פאנל נפתח המציג מועדפים שנשמרו עם תיקיות.',
    category: 'widget',
    filePath: 'components/command-center/widgets/FavoritesWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['folder-wrapper'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'today-widget',
    name: 'TodayWidget',
    nameHe: 'ווידג\'ט היום',
    description: 'Daily overview showing meetings, deadlines, and reminders from connected calendars.',
    descriptionHe: 'סקירה יומית המציגה פגישות, דדליינים ותזכורות מלוחות שנה מחוברים.',
    category: 'widget',
    filePath: 'components/command-center/widgets/TodayWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'notifications-widget',
    name: 'NotificationsWidget',
    nameHe: 'ווידג\'ט התראות',
    description: 'Notifications feed with read/unread state, red dot badge, and category filtering.',
    descriptionHe: 'פיד התראות עם מצב נקרא/לא נקרא, נקודה אדומה וסינון לפי קטגוריה.',
    category: 'widget',
    filePath: 'components/command-center/widgets/NotificationsWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'timer-widget',
    name: 'TimerWidget',
    nameHe: 'ווידג\'ט טיימר',
    description: 'Pomodoro timer with circular progress ring, work/break modes, and session tracking.',
    descriptionHe: 'טיימר פומודורו עם טבעת התקדמות, מצבי עבודה/הפסקה ומעקב פגישות.',
    category: 'widget',
    filePath: 'components/command-center/widgets/TimerWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'clipboard-widget',
    name: 'ClipboardWidget',
    nameHe: 'ווידג\'ט לוח הדבקות',
    description: 'Copy history within the dashboard. Stores and retrieves recently copied items.',
    descriptionHe: 'היסטוריית העתקה בדשבורד. שומר ומאחזר פריטים שהועתקו לאחרונה.',
    category: 'widget',
    filePath: 'components/command-center/widgets/ClipboardWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'settings-widget',
    name: 'SettingsWidget',
    nameHe: 'ווידג\'ט הגדרות',
    description: 'System widget (non-removable). Controls language, sidebar position, theme, and hover delay.',
    descriptionHe: 'ווידג\'ט מערכת (לא ניתן להסרה). שולט בשפה, מיקום סרגל צד, עיצוב וזמן ריחוף.',
    category: 'widget',
    filePath: 'components/command-center/widgets/SettingsWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['color-picker'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'shortcuts-widget',
    name: 'ShortcutsWidget',
    nameHe: 'ווידג\'ט קיצורים',
    description: 'Keyboard shortcuts modal. Shows all 41 system shortcuts organized by category with custom binding support.',
    descriptionHe: 'מודל קיצורי מקלדת. מציג 41 קיצורי מערכת מאורגנים לפי קטגוריה עם תמיכה בהתאמה.',
    category: 'widget',
    filePath: 'components/command-center/widgets/ShortcutsWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'weekly-planner-widget',
    name: 'WeeklyPlannerWidget',
    nameHe: 'ווידג\'ט תכנון שבועי',
    description: 'Weekly planning modal with daily task lists, recurring templates, and progress tracking.',
    descriptionHe: 'מודל תכנון שבועי עם רשימות משימות יומיות, תבניות חוזרות ומעקב התקדמות.',
    category: 'widget',
    filePath: 'components/command-center/widgets/WeeklyPlannerWidget.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'apps-drawer',
    name: 'AppsDrawer',
    nameHe: 'מגירת אפליקציות',
    description: 'Slide-out drawer showing widgets placed in "apps" mode. Alternative to toolbar placement.',
    descriptionHe: 'מגירה נשלפת המציגה ווידג\'טים במצב "אפליקציות". חלופה למיקום בסרגל.',
    category: 'widget',
    filePath: 'components/command-center/widgets/AppsDrawer.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'folder-wrapper',
    name: 'FolderWrapper',
    nameHe: 'עוטף תיקיות',
    description: 'Folder container for organizing favorites. Supports drag-reorder, emoji icons, and nested items.',
    descriptionHe: 'מכולת תיקיות לארגון מועדפים. תומך גרירה, אייקוני אמוג\'י ופריטים מקוננים.',
    category: 'widget',
    filePath: 'components/command-center/widgets/FolderWrapper.tsx',
    usedIn: ['/dashboard'],
    dependencies: ['folder-item-cell', 'folder-settings', 'folder-creator'],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'folder-item-cell',
    name: 'FolderItemCell',
    nameHe: 'תא פריט תיקיה',
    description: 'Individual item inside a folder — renders widget shortcut, navigation link, or quick action.',
    descriptionHe: 'פריט בודד בתוך תיקיה — מציג קיצור ווידג\'ט, קישור ניווט או פעולה מהירה.',
    category: 'widget',
    filePath: 'components/command-center/widgets/FolderItemCell.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'folder-settings',
    name: 'FolderSettings',
    nameHe: 'הגדרות תיקיה',
    description: 'Folder configuration panel for name, emoji, grid size, and item management.',
    descriptionHe: 'פאנל הגדרות תיקיה לשם, אמוג\'י, גודל רשת וניהול פריטים.',
    category: 'widget',
    filePath: 'components/command-center/widgets/FolderSettings.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
  {
    id: 'folder-creator',
    name: 'FolderCreator',
    nameHe: 'יוצר תיקיות',
    description: 'Inline form for creating new folders with name and emoji selection.',
    descriptionHe: 'טופס מוטבע ליצירת תיקיות חדשות עם בחירת שם ואמוג\'י.',
    category: 'widget',
    filePath: 'components/command-center/widgets/FolderCreator.tsx',
    usedIn: ['/dashboard'],
    dependencies: [],
    hasI18n: true,
    hasCcId: false,
    status: 'stable',
  },
];

// ─── Lookup functions ──────────────────────────────────────────────

const entryMap = new Map(componentRegistry.map(c => [c.id, c]));

export function getComponentById(id: string): ComponentEntry | undefined {
  return entryMap.get(id);
}

export function getComponentsByCategory(cat: ComponentCategory): ComponentEntry[] {
  return componentRegistry.filter(c => c.category === cat);
}

export function getComponentsUsedIn(route: string): ComponentEntry[] {
  return componentRegistry.filter(c => c.usedIn.includes(route));
}
